### ISSUE TITLE
Can not login via LINE apps.

### ISSUE THREAD

**Issue by kphetrungnapha** [line/line-sdk-starter-ios#10]
When I authorized at LINE apps and it called back to my apps, It's always error like this 

```
"Error Domain=LineAdapterErrorDomain Code=6 "The+operation+couldn’t+be+completed.+(NLChannelGatewayErrorDomain+error+102.)" UserInfo={LineAdapterAuthorizationResultCode=INTERNALERROR, NSLocalizedDescription=The+operation+couldn’t+be+completed.+(NLChannelGatewayErrorDomain+error+102.)}"
```

I have already double checked about configuration. It's all correct. However, I can login via LineAdapterWebViewController. Thank you for your suggestion.

**Comment by ha1f** [comment]
I have the same trouble.
I can authorize via LineAdapterWebViewController, but I can't authorize via LINE app.

```
操作を完了できませんでした。（NLChannelGatewayErrorDomain+エラー+102。）
```

**Comment by huakwan** [comment]
I have the same trouble.
The+operation+couldn’t+be+completed.+(NLChannelGatewayErrorDomain+error+102.)

**Comment by dolow** [comment]
Here too.

When I try to log in via LINE app (caling [adapter authorize]), it always returns the code _LineAdapterErrorAuthorizationFailed_ with the message

```
"操作を完了できませんでした。（NLChannelGatewayErrorDomain+エラー+102。）"
```

In LINE app, my app which called [adapter authorize] was properly added to Authorized Apps (連動アプリ) although LineAdapter doesn't recognize it is authorized.

On the other hand, logging in via LineAdapterWebViewController works fine.
but it requires users' e-mail address and I don't want to force users to register e-mail address.

This problem is only for iOS.
Android works fine without any problem.

**Comment by sarunw** [comment]
Got the same problem.

**Comment by mrmaakun** [comment]
"NLChannelGatewayErrorDomain Error 102" can occur if your iOS bundle ID is hasn't been properly registered in the "Technical Configuration" section of the Channel Console. 

Can you check to make sure that the an iOS Bundle ID has been registered and that it matches your application's iOS Bundle ID?

For iOS applications, you should always check the following items:
- Is the iOS Bundle ID registered in the Channel Console's "Technical Information" section?
- Is the iOS URL Scheme registered in the Channel Console's "Technical Information" section?
- Is the LINE account that you are using to log in registered in the "Roles" section of the Channel Console?

**Comment by ha1f** [comment]
Thank you for @mrmaakun !
The reason I couldn't login with app was the last point you mention.

I use another account to develop, so I haven't added "Roles" to that account.
If we set the app status "PUBLISHED", the authorization will able to authoralized by all people? Is this right?

**Comment by mrmaakun** [comment]
> I use another account to develop, so I haven't added "Roles" to that account.
> If we set the app status "PUBLISHED", the authorization will able to authoralized by all people? Is this right?

This is correct. If the app status is set to "DEVELOPING", only LINE accounts that are added to the "Roles" can log into the application. If the app status is set to "PUBLISHED", all LINE users will be able to log into the application.

**Comment by WWaVe** [comment]
a new problem here, i can't change my account to "PUBLISHED", how?

**Comment by mrmaakun** [comment]
It looks like this issue has been resolved so I will close it.

**Comment by budlover** [comment]
>> Is the iOS Bundle ID registered in the Channel Console's "Technical Information" section?

Hi @mrmaakun , is the bundle ID case sensitive? the bundle ID in 'Technical configuration' part (https://developers.line.me) only accept lowercase. 

But our app bundle identifier contains uppercase letter. I cannot change our app bundle ID easily.

**Comment by budlover** [comment]
It turns out that my bundle ID doesn't starts with line3rdp, which cause the error. Now it's working for me.

**Comment by budlover** [comment]
Hi @mrmaakun, one more following question, is the URL Scheme required to be in the format of this?
line3rdp.${Bundle ID}

can it be this format?
line3rdp.${Bundle ID}.${something else}

**Comment by mrmaakun** [comment]
@budlover

It must be in the format `line3rdp.${Bundle ID}`.
