### ISSUE TITLE
Post event issue

### ISSUE THREAD

**Issue by thienhaole92** [line/line-sdk-starter-ios#14]
- (void)postEventTo:(NSArray *)aMidArray
        toChannel:(NSString *)aChannelId
        eventType:(NSString *)aEventType
          content:(NSDictionary *)aContent
             push:(NSDictionary *)aPush
      resultBlock:(LineApiClientResultBlock)aResultBlock;

How to use this function? I want to post an image with hastag.
eventType:  which value for this?
content: key and value type for this?
push: key and value type for this

**Comment by GuitarSucks** [comment]
This starter is for LINE Login SDK. The SDK currently only provides social login and getProfile.
If you want to send a message from an @ account, you should use Messaging API.
