### ISSUE TITLE
Can Not Login LineAdapterErrorDomain error: 5

### ISSUE THREAD

**Issue by adhicl** [line/line-sdk-starter-ios#15]
Hi, I try to login with Line app and I got that return message. So far I can login with Line web view. What does error 5 means?

**Comment by mrmaakun** [comment]
Hello @adhicl,

Can you first check the following technical configuration items?
- Is the iOS Bundle ID registered in the Channel Console's "Technical Information" section?
- Is the iOS URL Scheme registered in the Channel Console's "Technical Information" section?
- Is the LINE account that you are using to log in registered in the "Roles" section of the Channel Console?

Also, can you tell me if you are seeing this problem in the starter application as it is in the repository or if you are seeing this in an application that you developed?

**Comment by adhicl** [comment]
Hi, I see this problem in an application I developed based on the starter. In starter it works but in my app it does not work. I use the same setting as in starter for the technical information. That is why I am confused why the error code 5?

**Comment by adhicl** [comment]
Hi, after I check I finally notice that my appcontroller is replaced and some codes are missing, especially the handlelaunchoptions one. After I add it, it finally works. Thank you for your help.
