### ISSUE TITLE
Bitcode error (Xcode 8)

### ISSUE THREAD

**Issue by aritaku** [line/line-sdk-starter-ios#17]
Bitcode error (Xcode 8)

When I archive with default settings of Xcode 8 project, I got following error.

```
LineAdapter.framework was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang
```

How can I deal with this?

**Comment by GuitarSucks** [comment]
I haven't had any report about this in Xcode 8 yet. Can you provide which version of LineAdpater you are using ?

**Comment by tericky** [comment]
@GuitarSucks , I have same problem with BitCode. The version I used is 3.2.1

Please open Project, and go to [Target] -> [Build Setting] -> [Build Options] -> [Enable BitCode], set it to Yes.

And then build project with [Archive], the error should be show up.

The Xcode project default setting is Yes, so, could you update the framework for fit this?

**Comment by shu223** [comment]
@GuitarSucks We also need bitcode supported version! Do you have some actual plan to release the bitcode supported version?

**Comment by aritaku** [comment]
@GuitarSucks  This problem occurred in version 3.2.1

**Comment by GuitarSucks** [comment]
Hi All
We released a fixed version. 
Sorry for the inconvenience.

----
The LINE SDK for iOS has been updated to version 3.2.2.
Changes:
1)Compatibility for bitcode added

You can download it from the LINE SDK archives on the following page:
https://developers.line.me/resources/download-sdk

**Comment by aritaku** [comment]
@GuitarSucks Thanks for quick and great release!

**Comment by shu223** [comment]
@GuitarSucks How fast! Thank you so much.

**Comment by tericky** [comment]
@GuitarSucks Thanks for release 😀
