### ISSUE TITLE
where is the 'LineAdapter.plist file' file?

### ISSUE THREAD

**Issue by budlover** [line/line-sdk-starter-ios#19]
The readme file shows:

Replace {YOUR_CHANNEL_ID} with your channel id (from https://developers.line.me/channels/) in LineAdapter.plist

But where is the LineAdapter.plist file? I cannot find it.

**Comment by budlover** [comment]
Should I create one? If so, what's the content in it?

**Comment by budlover** [comment]
I am asking this because I always get error when the app started:

2017-02-07 14:43:46.998 LineSDKStarterSwift[1846:18270] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [aChannelID length]'
*** First throw call stack:

**Comment by mrmaakun** [comment]
The information in this readme file is outdated. The LineAdapter.plist file was removed because it is no longer needed. You can now define your channel ID in your Info.plist file using the following key:

```xml
	<key>LineAdapterConfig</key>
	<dict>
		<key>ChannelId</key>
		<string>{YOUR_CHANNEL_ID}</string>
		<key>Phase</key>
		<string>REAL</string>
	</dict>
```

**Comment by budlover** [comment]
@mrmaakun thanks for help. Now it works :)

It's better to update the README file and add this part on:
https://developers.line.me/ios/development-with-sdk-v2#info_plist

so that other people won't miss it.

**Comment by budlover** [comment]
Hi Mark,

Thanks a lot for your help!

Actually we are at Uber, and working on LINE's login via Uber app. May I
know your working email? So that we can contact directly in case we have
more question about iOS SDK.

2017-02-07 22:30 GMT-08:00 Mark Serrano <notifications@github.com>:

**Comment by GuitarSucks** [comment]
Hi @budlover 
Sorry but we cant provide our contact. 
I think you have connections with our Thailand team so you can contact them directly.

Regards
