### ISSUE TITLE
Application should properly configured for handling URL

### ISSUE THREAD

**Issue by budlover** [line/line-sdk-starter-ios#20]
I am getting error when I try to login with LINE:

Application should properly configured for handling URL <line3rdp.my_app_id://authorize/>

Error shows on console:
2017-02-08 10:08:06.995 LineSDKStarterSwift[232:6826] -canOpenURL: failed for URL: "line3rdp.com.qiliu.logintest://authorize/" - error: "(null)"

**Comment by budlover** [comment]
BTW, this is my info.plist file:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>com.qiliu.logintest</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>CHANNEL_EDITOR</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>line3rdp.{PRODUCT_BUNDLE_IDENTIFIER}</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>lineauth</string>
		<string>line3rdp.$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>LineSDKConfig</key>
	<dict>
		<key>ChannelID</key>
		<string>{my channel id}</string>
	</dict>
	<key>LineAdapterConfig</key>
	<dict>
 		<key>ChannelId</key>
 		<string>{my channel id}</string>
	</dict>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</dict>
</plist>

**Comment by mrmaakun** [comment]
@budlover 

This error typically occurs if CFBundleURLSchemes is not set to "line3rdp." followed by your bundle identifier, in this case "line3rdp.com.qiliu.logintest".

In your info.plist file, it is set to `line3rdp.$(PRODUCT_BUNDLE_IDENTIFIER)`. Can you verify that Product Bundle Identifier is properly set in your build settings?

<img width="783" alt="screen shot 2017-02-08 at 15 24 20" src="https://cloud.githubusercontent.com/assets/497426/22725762/b9b6a380-ee12-11e6-9314-45cf95d05841.png">

**Comment by budlover** [comment]
@mrmaakun you are right! My "product bundle identifier" isn't set correctly. No I use fix the name and it works.

Thanks!
