### ISSUE TITLE
Have any sample of Implemented iOS SDK 4.0.0?

### ISSUE THREAD

**Issue by tk009999** [line/line-sdk-starter-ios#22]
According to the issue

**Comment by mrmaakun** [comment]
Hi @tk009999 

We have an Objective-C sample for iOS SDK 4.0.0 here:

https://github.com/line/line-sdk-starter-ios-v2

A Swift sample is also in the works. We will add it to this repository when it is finished.

**Comment by tk009999** [comment]
Thanks a lot @mrmaakun 
Actually, I finished Swift3.0 Sample for iOS SDK 4.0.1 in the morning
Cause I want implement function of LINE Sing In  to my project, so I try to programed
May I send to you guys ?  or May I deploy?

**Comment by mrmaakun** [comment]
@tk009999 

We went ahead and added a Swift sample to the starter: 
https://github.com/line/line-sdk-starter-ios-v2

But we appreciate you offering your sample!
