### ISSUE TITLE
Why my app get this info.plist error in LineSDK.framework ?

### ISSUE THREAD

**Issue by abadikaka** [line/line-sdk-starter-ios#23]
Failed to load Info.plist from bundle at path /Users/macbook/Library/Developer/CoreSimulator/Devices/41037EA7-889D-4E80-8FBD-E39D221F3FFA/data/Library/Caches/com.apple.mobile.installd.staging/temp.6xEwC2/extracted/MYAPP.app/Frameworks/LineSDK.framework

i have added neccessary client_id and url_scheme as well

any ideas ?

**Comment by mrmaakun** [comment]
Hi @abadikaka,

Can you try the following and check to see if the problem still occurs?

* Clean the build folder by holding the option key and clicking on Product -> Clean Build Folders
* Restart the iPhone simulator
* If restarting the iPhone Simulator doesn't work, try resetting the simulator by going to Simulator -> Reset Content and Settings.

If none of these solve the issue, can you provide a project that the problem occurs in?

**Comment by abadikaka** [comment]
Hi @mrmaakun yeah. i already try that but not working, anyway then i try remove the linesdk and linking it once more again and now succesfull,
but i got this problem when starting to login

failed for URL: "line3rdp.org.reactjs.native.example.MYAPP://authorize/" - error: "This app is not allowed to query for scheme line3rdp.org.reactjs.native.example.MYAPP..

do u know why i got that error ? I have set my scheme correct,
