### ISSUE TITLE
We want to publish in Cocoapods

### ISSUE THREAD

**Issue by Mizogaki** [line/line-sdk-starter-ios#3]
We want to publish in Cocoapods

[![Cocoapod](http://shrikar.com/wp-content/uploads/2015/01/cocoapods.png)](https://guides.cocoapods.org/)

**Comment by GuitarSucks** [comment]
@MMizogaki 
Let me check.
Thanks

**Comment by mrmaakun** [comment]
We have published Line SDK 4.0.2 for iOS on Cocoapods: https://developers.line.me/ios/development-with-sdk-v2#cocoapods

Sorry for the wait.
