### ISSUE TITLE
Swift 2.3 and 2.3 support

### ISSUE THREAD

**Issue by ghost** [line/line-sdk-starter-ios#6]
The codebase is outdated and should be updated to Swift 2.3 or preferably 3.0

Both the demo app and the framework. In the framework, the JSON structure of the answer should hopefully be set as value-type or enum, so we can securely read the data from the JSOn answer, rather than reading it as a string based dictionary.

Thank you.

**Comment by GuitarSucks** [comment]
@EinFinc 
Will be added soon by my collogue.

**Comment by GuitarSucks** [comment]
https://developers.line.me/news/ios/the-line-sdk-for-ios-3-2-1-released-and-the-line-starter-application-revised
