### ISSUE TITLE
Demo：Login error!

### ISSUE THREAD

**Issue by JinghuangLiu** [line/line-sdk-starter-ios#9]
Error Domain=LineAdapterErrorDomain Code=10 "(null)" UserInfo={statusMessage=internal error., statusCode=500}

**Comment by JinghuangLiu** [comment]
Now we are meeting this problem , everything of info.plist is setted and the network is fine. Run the Demo click the "LOGIN with LINE" or "LOGIN in app" button, and the error message is like that. We can not do other thing to check it, please check it for us.

**Comment by GuitarSucks** [comment]
@JinghuangLiu 
Will update this starter kit soon, and upload new sdk version.
It might solve your issue.

**Comment by GuitarSucks** [comment]
https://developers.line.me/news/ios/the-line-sdk-for-ios-3-2-1-released-and-the-line-starter-application-revised

**Comment by GuitarSucks** [comment]
closing this issue for now.
